export const STEM_TEMPLATE = {
  slug: "national-stem-entrance-2026",
  name: "National STEM Entrance 2026",
  externalPortalName: "National STEM Entrance candidate portal",
  description: "Undergraduate engineering entrance application with identity, academic, and declaration fields.",
  category: "Education · Undergraduate",
  fieldCount: 38,
  deadline: "2026-09-10",
} as const;

export const STEM_REQUIREMENTS = [
  {
    key: "full_name",
    label: "Full name",
    dataType: "text",
    sourceKey: "full_name",
    sourceProvider: "meripehchaan",
    needsUserDecision: false,
  },
  {
    key: "date_of_birth",
    label: "Date of birth",
    dataType: "date",
    sourceKey: "date_of_birth",
    sourceProvider: "meripehchaan",
    needsUserDecision: false,
  },
  {
    key: "parent_guardian",
    label: "Parent / guardian",
    dataType: "text",
    sourceKey: "parent_guardian",
    sourceProvider: "manual",
    needsUserDecision: false,
  },
  {
    key: "category",
    label: "Category",
    dataType: "text",
    sourceKey: "category",
    sourceProvider: "meripehchaan",
    needsUserDecision: false,
  },
  {
    key: "annual_family_income",
    label: "Annual family income",
    dataType: "currency",
    sourceKey: "annual_family_income",
    sourceProvider: "manual",
    needsUserDecision: true,
  },
  {
    key: "mobile_number",
    label: "Mobile number",
    dataType: "phone",
    sourceKey: "mobile_number",
    sourceProvider: "meripehchaan",
    needsUserDecision: false,
  },
  {
    key: "email_address",
    label: "Email address",
    dataType: "email",
    sourceKey: "email_address",
    sourceProvider: "manual",
    needsUserDecision: false,
  },
  {
    key: "academic_record",
    label: "Academic record",
    dataType: "text",
    sourceKey: "academic_record",
    sourceProvider: "apaar",
    needsUserDecision: false,
  },
  {
    key: "class_xii_marksheet",
    label: "Class XII marksheet",
    dataType: "document",
    sourceKey: "class_xii_marksheet",
    sourceProvider: "digilocker",
    needsUserDecision: false,
  },
  {
    key: "identity_verification",
    label: "Identity verification",
    dataType: "verification",
    sourceKey: "identity_verified",
    sourceProvider: "meripehchaan",
    needsUserDecision: false,
  },
  {
    key: "exam_city",
    label: "Exam city preference",
    dataType: "text",
    sourceKey: null,
    sourceProvider: null,
    needsUserDecision: true,
  },
  {
    key: "declaration",
    label: "Declaration",
    dataType: "boolean",
    sourceKey: null,
    sourceProvider: null,
    needsUserDecision: true,
  },
] as const;

export const DEMO_PROFILE = {
  fullName: "Aanya Mehta",
  email: "aanya.mehta.demo@example.com",
  phone: "+91 98••• 48126",
  dateOfBirth: "2005-08-14",
  city: "Pune",
  state: "Maharashtra",
  category: "General",
  annualFamilyIncome: "₹4,80,000",
  parentGuardian: "Nikhil Mehta",
  academicRecord: "Class XII · 91.4%",
} as const;

export const DEMO_SOURCES = [
  {
    provider: "meripehchaan",
    displayName: "MeriPehchaan",
    detail: "Identity, address, mobile",
    status: "connected",
  },
  {
    provider: "digilocker",
    displayName: "DigiLocker",
    detail: "Class X & XII certificates",
    status: "connected",
  },
  {
    provider: "apaar",
    displayName: "APAAR",
    detail: "Academic record · updated today",
    status: "connected",
  },
] as const;
