/** Repeatable API/route audit against a seeded sandbox; never run on production data. */
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base=process.env.AUDIT_BASE_URL??'http://localhost:3300';
const portal=process.env.AUDIT_PORTAL_URL??'http://localhost:3301';
if(![base,portal].every(url=>['localhost','127.0.0.1'].includes(new URL(url).hostname))) throw new Error('Audit requires a local sandbox');
const results=[];
async function test(name,fn){const start=Date.now();try{await fn();results.push({name,passed:true,ms:Date.now()-start});console.log(`PASS ${name}`);}catch(e){results.push({name,passed:false,ms:Date.now()-start,error:e.message});console.log(`FAIL ${name}: ${e.message}`);}}
function client(){const jar=new Map();return async(path,method='GET',data,headers={})=>{
 const url=new URL(path,base);
 const response=await fetch(url,{method,redirect:'manual',signal:AbortSignal.timeout(180000),headers:{cookie:[...jar].map(([k,v])=>`${k}=${v}`).join('; '),...(data && !(data instanceof FormData)?{'content-type':'application/json'}:{}),...headers},body:data instanceof FormData?data:data===undefined?undefined:JSON.stringify(data)});
 for(const c of response.headers.getSetCookie()){const value=c.split(';')[0];const i=value.indexOf('=');jar.set(value.slice(0,i),value.slice(i+1));}
 const text=await response.text();let json;try{json=JSON.parse(text);}catch{}
 return {status:response.status,json,text,location:response.headers.get('location'),headers:response.headers};
};}
async function login(c,phone){let r=await c('/api/auth/phone-number/send-otp','POST',{phoneNumber:`+91${phone}`},{origin:base});assert.equal(r.status,200);r=await c('/api/auth/phone-number/verify','POST',{phoneNumber:`+91${phone}`,code:'123456'},{origin:base});assert.equal(r.status,200);}
const anonymous=client(),citizen=client(),guardian=client(),partner=client(),admin=client(),bta=client();
const key={authorization:`Bearer ${process.env.BTA_APPLYONCE_API_KEY??'pk_sandbox_bta_demo_key_0001'}`};
let profile,ward,foreign,formId,consentId,applicationId,session,shareToken,extensionToken,doc;
await test('anonymous APIs require authentication',async()=>{for(const path of ['/api/v1/profiles','/api/v1/applications','/api/v1/notifications','/api/v1/admin/overview'])assert.equal((await anonymous(path)).status,401,path);});
await test('citizen OTP login and profile list',async()=>{await login(citizen,'9876543210');const r=await citizen('/api/v1/profiles');assert.equal(r.status,200);profile=r.json.data.activeProfileId;assert.ok(profile);});
await test('guardian scope remains limited',async()=>{await login(guardian,'9876500002');const r=await guardian('/api/v1/profiles');ward=r.json.data.profiles.find(p=>p.displayName.includes('Kamla'));foreign=r.json.data.activeProfileId;assert.ok(ward);assert.deepEqual(ward.scope,['identity','health','bank']);assert.equal((await guardian(`/api/v1/profiles/${ward.id}/facts?section=education`)).status,403);assert.equal((await citizen(`/api/v1/profiles/${foreign}/facts`)).status,403);});
await test('cross-origin mutations rejected',async()=>assert.equal((await citizen('/api/v1/me','PATCH',{locale:'en'},{origin:'https://malicious.invalid'})).status,403));
await test('ordinary citizen cannot call admin',async()=>assert.equal((await citizen('/api/v1/admin/overview')).status,403));
await test('passkey step-up cannot be faked with fresh OTP session',async()=>assert.equal((await citizen('/api/v1/auth/step-up','POST',{method:'passkey'})).status,401));
await test('sensitive document needs step-up',async()=>{const r=await citizen(`/api/v1/profiles/${profile}/documents`);const documents=r.json.data.documents??r.json.data;doc=documents.find(d=>d.docType==='marksheet_12'&&d.storageKey?.startsWith('mock/'))??documents.find(d=>d.docType==='marksheet_12');assert.ok(doc);assert.equal((await citizen(`/api/v1/documents/${doc.id}/download-url`)).status,403);});
await test('OTP step-up and revocable sample preview',async()=>{assert.equal((await citizen('/api/v1/auth/step-up','POST',{method:'otp',code:'000000'})).status,401);assert.equal((await citizen('/api/v1/auth/step-up','POST',{method:'otp',code:'123456'})).status,200);const r=await citizen(`/api/v1/documents/${doc.id}/download-url`);assert.equal(r.status,200);assert.ok(r.json.data.url.includes('ticket='));assert.equal((await anonymous(r.json.data.url)).status,200);assert.equal((await anonymous(r.json.data.url+'tamper')).status,401);});
await test('foreign and wrong-type document references rejected',async()=>{const foreignDocs=await guardian(`/api/v1/profiles/${foreign}/documents`);const first=(foreignDocs.json.data.documents??foreignDocs.json.data)[0];assert.ok(first);for(const id of [first.id,doc.id])assert.equal((await citizen(`/api/v1/profiles/${profile}/facts/identity.photo`,'PUT',{value:id})).status,400);});
await test('provider cannot import guardian identity into a dependent',async()=>assert.equal((await guardian(`/api/v1/providers/digilocker/sync?profile=${ward.id}`,'POST',{})).status,403));
await test('registered partner redirect origin enforced',async()=>{const r=await anonymous('/api/v1/partner/share-sessions','POST',{form_slug:'bta-jee-2026',return_url:'https://malicious.invalid/callback'},key);assert.equal(r.status,422);assert.equal(r.json.error.code,'RETURN_URL_NOT_ALLOWED');});
await test('declining consent invalidates the link',async()=>{const r=await anonymous('/api/v1/partner/share-sessions','POST',{form_slug:'bta-jee-2026',return_url:`${base}/app/applications`},key);assert.equal(r.status,200);const token=new URL(r.json.data.share_url).pathname.split('/').pop();assert.equal((await citizen(`/api/v1/share/${token}`,'DELETE')).status,200);assert.equal((await citizen(`/api/v1/share/${token}`)).status,410);});
await test('BTA start creates browser-bound state and real share session',async()=>{const r=await bta(`${portal}/api/applyonce/session`,'POST');assert.equal(r.status,303);shareToken=new URL(r.location).pathname.split('/').pop();const preview=await citizen(`/api/v1/share/${shareToken}`);assert.equal(preview.status,200);session=preview.json.data;formId=session.form.id;});
await test('readiness guide works without sharing identity values',async()=>{const r=await citizen('/api/v1/readiness','POST',{formId,profileId:profile,intent:'next',locale:'en'});assert.equal(r.status,200);assert.ok(r.json.data.summary);assert.equal(JSON.stringify(r.json).includes('Aarav'),false);});
await test('tampered custom choices are rejected',async()=>{const r=await citizen(`/api/v1/share/${shareToken}/consent`,'POST',{profileId:profile,acceptedFields:[],customAnswers:{paper:'Injected option'}});assert.equal(r.status,422);});
await test('scoped guardian cannot consent to out-of-scope form',async()=>{await guardian('/api/v1/auth/step-up','POST',{method:'otp',code:'123456'});const r=await guardian(`/api/v1/share/${shareToken}/consent`,'POST',{profileId:ward.id,acceptedFields:[]});assert.equal(r.status,403);});
await test('consent produces an application and signed partner callback',async()=>{
 const files=Object.fromEntries(session.documents.map(d=>[d.docType,d.id]));
 assert.ok(files.photo,'seeded profile must include a ready photo');assert.ok(files.signature,'seeded profile must include a ready signature');
 const newFacts={'identity.photo':files.photo,'identity.signature':files.signature,'address.current.line1':'12 Gomti Nagar','address.current.village_town':'Lucknow','address.current.district':'Lucknow','address.current.state':'Uttar Pradesh','address.current.pincode':'226010'};
 const customAnswers={exam_city_1:'Lucknow',exam_city_2:'Delhi',paper:'Paper 1 (B.E./B.Tech)',medium:'English',declaration:true};
 const r=await citizen(`/api/v1/share/${shareToken}/consent`,'POST',{profileId:profile,acceptedFields:session.form.requested_fields.map(f=>f.key),newFacts,customAnswers});assert.equal(r.status,200,r.json?.error?.message);consentId=r.json.data.consent_id;applicationId=r.json.data.application_id;
 const callback=await bta(r.json.data.return_url);assert.equal(callback.status,307);assert.ok(callback.location.includes('draft='),callback.location);const review=await bta(callback.location);assert.equal(review.status,200);assert.ok(review.text.includes('Application pre-filled by ApplyOnce'));assert.equal((await bta(callback.location)).status,200);
 const unauthorized=await anonymous(callback.location);assert.equal(unauthorized.text.includes('Application pre-filled by ApplyOnce'),false);
});
await test('BTA submission rejects forged review sessions',async()=>{const f=new FormData();f.set('draft_token','forged');assert.equal((await bta(`${portal}/api/return/submit`,'POST',f)).status,403);});
await test('extension token cannot be passed in query or access system facts',async()=>{const token=await citizen('/api/v1/extension/token','POST');assert.equal(token.status,200);extensionToken=token.json.data.token;const path=`/api/v1/extension/fill-plan?profile=${profile}&keys=identity.aadhaar_ref_key,identity.full_name`;assert.equal((await anonymous(path+`&token=${extensionToken}`)).status,401);const r=await anonymous(path,'GET',undefined,{authorization:`Bearer ${extensionToken}`});assert.equal(r.status,200);assert.ok(r.json.data.values['identity.full_name']);assert.equal(r.json.data.values['identity.aadhaar_ref_key'],undefined);const link=await anonymous(`/api/v1/extension/documents/${doc.id}/url`,'GET',undefined,{authorization:`Bearer ${extensionToken}`});assert.ok(!link.json.data.url.includes(extensionToken));});
await test('upload size and MIME validation',async()=>{const path=`/api/v1/profiles/${profile}/documents/upload-url`;for(const data of [{filename:'large.pdf',mime:'application/pdf',size:16*1024*1024,docType:'other'},{filename:'script.html',mime:'text/html',size:100,docType:'other'}])assert.equal((await citizen(path,'POST',data)).status,422);});
await test('real file upload completes processing and is downloadable',async()=>{
 const bytes=Buffer.from('%PDF-1.4\n1 0 obj << /Type /Catalog >> endobj\n%%EOF');
 const created=await citizen(`/api/v1/profiles/${profile}/documents/upload-url`,'POST',{filename:'audit-sample.pdf',mime:'application/pdf',size:bytes.length,docType:'other'});assert.equal(created.status,200);const {url,documentId}=created.json.data;
 assert.equal((await fetch(url,{method:'PUT',headers:{'content-type':'application/pdf'},body:bytes})).status,200);
 assert.equal((await citizen(`/api/v1/documents/${documentId}/complete`,'POST',{size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')})).status,200);
 let r;for(let n=0;n<30;n++){r=await citizen(`/api/v1/documents/${documentId}`);if((r.json.data.document??r.json.data).status!=='pending')break;await new Promise(resolve=>setTimeout(resolve,1000));}
 const d=r.json.data.document??r.json.data;assert.equal(d.status,'ready',JSON.stringify(r.json));assert.equal((await citizen(`/api/v1/documents/${documentId}/download-url`)).status,200);
});
await test('erasure can be scheduled and explicitly cancelled',async()=>{await citizen('/api/v1/auth/step-up','POST',{method:'otp',code:'123456'});const r=await citizen('/api/v1/me/erase','POST',{confirm:'DELETE'});assert.equal(r.status,201);const cancelled=await citizen('/api/v1/me/erase','DELETE');assert.equal(cancelled.status,200);assert.equal(cancelled.json.data.cancelled,1);});
await test('declaration is stored with its full text and downloadable receipt',async()=>{
 const declaration='I confirm this is a synthetic audit declaration and does not assert a real identity.';
 const r=await citizen('/api/v1/declarations','POST',{title:'Audit declaration',declaration,confirm:true});assert.equal(r.status,201);
 const link=await citizen(`/api/v1/documents/${r.json.data.documentId}/download-url`);assert.equal(link.status,200);
 const receipt=await fetch(link.json.data.url);assert.equal(receipt.status,200);const text=await receipt.text();assert.ok(text.includes(declaration));assert.ok(text.includes('SHA-256'));
});
await test('data export queues successfully',async()=>assert.equal((await citizen('/api/v1/me/export','POST',{})).status,201));
await test('partner and administrator login',async()=>{await login(partner,'9000000001');await login(admin,'9000000000');assert.equal((await admin('/api/v1/admin/overview')).status,200);});
const citizenPages=['/app','/app/vault',...['identity','contact','address','family','category','education','employment','bank','health','prefs'].map(s=>`/app/vault/${s}`),'/app/apply','/app/apply/bta-jee-2026','/app/apply/nova-btech-2026','/app/apply/savings-account-kyc','/app/applications','/app/documents','/app/verify','/app/sign','/app/connections','/app/family','/app/settings','/app/settings/notifications','/app/notifications','/app/extension','/app/extension/connect'];
if(doc?.id)citizenPages.push(`/app/documents/${doc.id}`);if(applicationId)citizenPages.push(`/app/applications/${applicationId}`);if(consentId)citizenPages.push(`/app/connections/${consentId}`);
const pages={public:['/','/demo','/for-institutions','/privacy','/security','/terms','/dpo','/status','/auth/login'],citizen:citizenPages,partner:['/partner','/partner/forms','/partner/forms/new','/partner/applicants','/partner/developers','/partner/team','/partner/settings'],admin:['/admin','/admin/partners','/admin/providers','/admin/queues','/admin/flags','/admin/audit','/admin/requests']};
for(const [role,paths] of Object.entries(pages)){const c={public:anonymous,citizen,partner,admin}[role];for(const path of paths)await test(`${role} page ${path}`,async()=>{const r=await c(path);assert.equal(r.status,200);assert.ok(!r.text.includes('Internal Server Error'));assert.ok(!r.text.includes('NEXT_HTTP_ERROR_FALLBACK;500'));});}
for(const path of ['/','/apply/manual','/apply/return?error=state','/status/unknown'])await test(`BTA page ${path}`,async()=>{const r=await bta(`${portal}${path}`);assert.equal(r.status,path.startsWith('/status/')?404:200);});
await test('revocation blocks partner status changes',async()=>{assert.ok(consentId,'consent flow did not produce a consent ID');assert.ok(applicationId,'consent flow did not produce an application ID');assert.equal((await citizen(`/api/v1/consents/${consentId}/revoke`,'POST')).status,200);const r=await anonymous(`/api/v1/partner/applications/${applicationId}/status`,'POST',{status:'under_review'},key);assert.equal(r.status,409);});
const output=process.env.AUDIT_OUTPUT??'docs/audit-results.json';await mkdir(new URL('.',new URL(output,`file://${process.cwd()}/`)),{recursive:true});await writeFile(output,JSON.stringify({at:new Date().toISOString(),base,portal,passed:results.filter(r=>r.passed).length,total:results.length,results},null,2)+'\n');
console.log(`${results.filter(r=>r.passed).length}/${results.length} checks passed`);if(results.some(r=>!r.passed))process.exitCode=1;
