import {afterAll,beforeAll,describe,it,expect,vi} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {normalizeDateInput,validateValue} from '../../../demo-exam-portal/src/lib/validation';
import {FIELDS} from '../../../demo-exam-portal/src/lib/fields';
import {exchangeShareToken,type ApplyOnceConfig} from '../../../demo-exam-portal/src/lib/applyonce';
import {isApplicationStatusTransitionAllowed} from '@applyonce/schema';
let store:typeof import('../../../demo-exam-portal/src/lib/store');
let dir:string;
beforeAll(async()=>{dir=mkdtempSync(join(tmpdir(),'applyonce-portal-test-'));vi.stubEnv('DEMO_DATA_DIR',dir);store=await import('../../../demo-exam-portal/src/lib/store');});
afterAll(()=>{vi.unstubAllEnvs();rmSync(dir,{recursive:true,force:true});});
describe('BTA review and validation',()=>{
 it('rejects impossible dates in either supported format',()=>{expect(normalizeDateInput('2026-02-31')).toBeNull();expect(normalizeDateInput('31/02/2026')).toBeNull();expect(normalizeDateInput('2007-03-14')).toBe('2007-03-14');const dob=FIELDS.find(f=>f.isDate)!;expect(validateValue(dob,'2007-03-14').ok).toBe(true);});
 it('rejects arbitrary options and preserves false checkbox answers',()=>{const select=FIELDS.find(f=>f.kind==='select')!;expect(validateValue(select,'not-a-choice').ok).toBe(false);const bool=FIELDS.find(f=>f.kind==='checkbox'&&!f.mustBeChecked)!;expect(validateValue(bool,false)).toEqual({ok:true,value:false});});
 it('consumes callback state once',()=>{store.rememberState('nonce','session');expect(store.consumeState('nonce')).toBe('session');expect(store.consumeState('nonce')).toBeNull();});
 it('retains review drafts across refresh and records submission',()=>{store.saveDraft('draft',{payload:{} as never,verified:true,offline:false,createdAt:Date.now()});expect(store.getDraft('draft')).toBeTruthy();expect(store.getDraft('draft')).toBeTruthy();store.completeDraft('draft','BTA-ref');expect(store.getDraft('draft')?.submittedRef).toBe('BTA-ref');store.saveDraft('expired',{payload:{} as never,verified:true,offline:false,createdAt:Date.now()-31*60000});expect(store.getDraft('expired')).toBeUndefined();});
 it('rejects offline tokens unless fixture mode was explicitly enabled',async()=>{const cfg:ApplyOnceConfig={apiUrl:'http://localhost:1',apiKey:'test',formSlug:'test',webhookSecret:'test',selfUrl:'http://localhost:1',offline:false};await expect(exchangeShareToken(cfg,'sess_offline_x','offline:x')).rejects.toThrow('explicitly enabled');});
 it('prevents contradictory terminal status changes',()=>{expect(isApplicationStatusTransitionAllowed('under_review','accepted')).toBe(true);expect(isApplicationStatusTransitionAllowed('accepted','rejected')).toBe(false);expect(isApplicationStatusTransitionAllowed('rejected','accepted')).toBe(false);});
});
