import type { Metadata } from "next";
import Link from "next/link";
import { Prose, H2, P, UL, Block } from "@/components/public/blocks";
export const metadata: Metadata = { title: "Privacy notice", description: "Praman's DPDP Act 2023 privacy notice: what we collect, why, how long, your rights, children's data, and how to reach our Data Protection Officer." };
export default function Privacy() {
  return (
    <Prose title="Privacy notice" updated="2 September 2026" intro="This is our notice under the Digital Personal Data Protection Act 2023 and the DPDP Rules 2025. It is itemised on purpose: for each kind of data, why we use it, and how to withdraw. If you only read one section, read 'Your rights'.">
      <Block><H2>Who we are</H2><P>Praman ("we") is the Data Fiduciary for your Praman account. Institutions you share with (exam boards, universities, banks) are separate Data Fiduciaries for what they receive. Our Data Protection Officer: <a className="underline" href="mailto:dpo@praman.in">dpo@praman.in</a>, Praman Technologies, Lucknow, India.</P></Block>
      <Block><H2>What we collect and why (itemised)</H2>
        <div className="overflow-x-auto rounded-lg border border-line"><table className="w-full min-w-[640px] text-sm"><thead className="bg-surface-2 text-left text-xs uppercase tracking-[0.04em] text-ink-3"><tr><th className="px-3 py-2">Category</th><th className="px-3 py-2">Examples</th><th className="px-3 py-2">Purpose</th><th className="px-3 py-2">Source</th></tr></thead><tbody className="divide-y divide-line">
          {[["Identity", "Name, DOB, gender, photo, PAN, Aadhaar last-4", "Fill and verify your applications", "You, DigiLocker/UIDAI, Income Tax"], ["Contact & address", "Mobile, email, permanent/current address", "Reach you; fill forms", "You, OTP, Aadhaar offline"], ["Family & income", "Parent names, occupation, annual income", "Scholarship and category eligibility", "You, e-District, Account Aggregator (opt-in)"], ["Category & eligibility", "Social category, PwD, domicile, certificates", "Reservation and fee eligibility", "DigiLocker, e-District"], ["Education", "Boards, roll numbers, marks, degrees", "Admissions and exams", "CBSE/CISCE/NAD via DigiLocker"], ["Employment & bank", "Employer, CTC, account number (masked), IFSC", "Jobs, KYC, scholarship payouts", "You, penny-drop, AA"], ["Health (opt-in)", "Blood group, ABHA, emergency contact", "Only if you enable it; hospital forms", "You, ABDM"], ["Technical", "Device, IP hash, session, audit rows", "Security and your audit log", "Automatic"]].map((r) => <tr key={r[0]}>{r.map((c, i) => <td key={i} className="px-3 py-2 align-top">{c}</td>)}</tr>)}
        </tbody></table></div>
        <P>We do not collect: your full Aadhaar number, biometrics, location history, or anything for advertising.</P></Block>
      <Block><H2>Legal basis and consent</H2><UL items={["Storing your vault: your consent when you create an account (withdraw by deleting the account).", "Each share with an institution: a separate, specific consent you give on the share screen, with fields, purpose and expiry listed one per row. Withdraw from Connections → Revoke; the institution is notified.", "Verifying with issuers (DigiLocker, PAN, ABHA, AA): you authorise each connection on the issuer's own consent page."]} /></Block>
      <Block><H2>Children's data</H2><P>A child is anyone under 18. A parent or guardian creates and manages a child's profile as the verifiable parent (we verify the parent's identity via DigiLocker, the mechanism named in DPDP Rule 10). We never profile, track or target children. When the child turns 18 we send them a claim link; the profile becomes theirs and the guardian's access reduces to identity and education for 90 days, then ends.</P></Block>
      <Block><H2>How long we keep it</H2><UL items={["Your vault: while your account exists.", "Shares: the institution's stated retention (shown before you consent; default 365 days), after which the payload is deleted on our side.", "Consent records and audit rows: 7 years (Consent Manager rule) — these are kept even after account deletion, without the underlying personal data.", "Deleted accounts: 30-day grace during which logging in cancels deletion; then hard delete, except records under legal hold."]} /></Block>
      <Block><H2 id="rights">Your rights</H2><UL items={[<>Access: download everything from Settings → Privacy & data, or via the <Link href="/dpo" className="underline">rights form</Link>.</>, "Correction: edit self-declared values any time; for issuer-verified values we help you re-fetch from the issuer.", "Erasure: delete your account (30-day grace).", "Withdraw consent: revoke any share; it is as easy as giving it.", "Nominate: name someone to exercise these rights if you are incapacitated (Settings → Privacy, coming with Phase 3).", "Grievance: dpo@praman.in — we reply within 30 days. Unsatisfied? Escalate to the Data Protection Board of India."]} /></Block>
      <Block><H2>Sharing and transfers</H2><P>We share only with institutions you choose, and with processors that run our infrastructure (cloud hosting in India, SMS delivery, verification APIs). Data stays in India. We do not sell or rent data.</P></Block>
      <Block><H2>Breach notification</H2><P>If a breach affects you, we notify you and the Data Protection Board without delay, and file a detailed report within 72 hours (DPDP Rule 7) in addition to CERT-In's 6-hour notice.</P></Block>
      <Block><H2>Changes</H2><P>We will notify you in-app before material changes take effect. Previous versions are available on request.</P></Block>
    </Prose>
  );
}
