import Link from "next/link";
import { Prose,H2,P,UL,Block } from "@/components/public/blocks";
export const metadata={title:"Privacy notice"};
export default function Privacy(){return <Prose title="Sandbox privacy notice" updated="6 September 2026" intro="Praman is a working demonstration of a consent-based application vault. Use sample data in this environment. This notice describes current behavior; it is not a claim of regulatory certification.">
<Block><H2>What is stored</H2><P>Your account, profile facts, uploaded documents, family permissions, applications, consent receipts and activity records are stored by the application. Mock provider connections return seeded records. Sensitive fact values are encrypted; the local database and file storage still require production hardening.</P></Block>
<Block><H2>Sharing with an institution</H2><UL items={["You see the requested fields, purpose and retention period before approval. Optional fields can be excluded.","A fresh OTP or passkey confirmation creates a consent receipt and a signed payload containing the approved fields and document fingerprints.","Connections lets you inspect and revoke consent. Revocation blocks further Praman access and sends a signed webhook to the partner. It cannot remotely erase copies already held by an external institution."]}/></Block>
<Block><H2>Family access</H2><P>Minor profiles can be managed by their guardian. Adults approve a scoped invite using their own phone login. Delegated access expires or can be removed. Age and guardian identity checks in this demo are not a substitute for production identity verification.</P></Block>
<Block><H2>Optional AI explanations</H2><P>The readiness score is computed locally. Without an AI key, the guide also runs locally. When configured, OpenAI receives field labels and derived next-step guidance, without profile values, names, documents or user identifiers. Requests use store: false; account and provider policies still govern service-side processing.</P></Block>
<Block><H2 id="rights">Your controls</H2><UL items={[<>Edit facts in <Link className="underline" href="/app/vault">Vault</Link>; re-verify issuer values instead of silently replacing them.</>,<>Export compressed JSON and schedule or cancel account deletion in <Link className="underline" href="/app/settings?tab=privacy">Settings</Link>. Document files are downloaded separately.</>,"Account deletion has a 30-day grace period. Cancel explicitly before processing. Recent active applications can place the request on hold.",<>Use the <Link className="underline" href="/dpo">data-request form</Link> for a request that needs operator review. It appears in the admin request queue.</>]}/></Block>
<Block><H2>Retention and deployment</H2><P>Consent expiry prevents new payload access. Automated deletion of every historical payload, backup retention, object-store cleanup and jurisdiction-specific legal policies require a production lifecycle plan. The repository documents these remaining launch requirements.</P></Block>
</Prose>;}
